### ISSUE TITLE
Catalog and threads won't load with specific networks

### ISSUE THREAD

**Issue by uenoshita** [Floens/Clover#361]
Catalog and threads won't load with specific networks

When trying to access 4chan via clover with my home dsl connection I can't get the threads or boards to load. Opening Firefox/chrome allows to load 4chan. Also I tried using a vpn and clover works just fine with that.

Open clover.
Load boards. Boards won't load.

Android version: 7.1.2
Phone model: Xiaomi Redmi note 3 pro (Kenzo)
Clover version: V2.3.1 F-Droid

Logfile
```
I/Clover | ChanLoader: Loading error
I/Clover | ChanLoader: com.a.a.z
I/Clover | ChanLoader: 	at com.a.a.b.a.a(BasicNetwork.java:137)
I/Clover | ChanLoader: 	at com.a.a.k.run(NetworkDispatcher.java:110)
I/Clover | ChanLoader: Loading error
I/Clover | ChanLoader: com.a.a.n: java.net.ConnectException: Connection refused
I/Clover | ChanLoader: 	at com.a.a.b.a.a(BasicNetwork.java:148)
I/Clover | ChanLoader: 	at com.a.a.k.run(NetworkDispatcher.java:110)
I/Clover | ChanLoader: Caused by: java.net.ConnectException: Connection refused
I/Clover | ChanLoader: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
I/Clover | ChanLoader: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
I/Clover | ChanLoader: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
I/Clover | ChanLoader: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
I/Clover | ChanLoader: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
I/Clover | ChanLoader: 	at java.net.Socket.connect(Socket.java:605)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
I/Clover | ChanLoader: 	at com.android.okhttp.Connection.connectSocket(Connection.java:196)
I/Clover | ChanLoader: 	at com.android.okhttp.Connection.connect(Connection.java:172)
I/Clover | ChanLoader: 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
I/Clover | ChanLoader: 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
I/Clover | ChanLoader: 	at com.a.a.b.l.a(HurlStack.java:112)
I/Clover | ChanLoader: 	at com.a.a.b.a.a(BasicNetwork.java:96)
I/Clover | ChanLoader: 	... 1 more
I/Clover | ChanLoader: Loading error
I/Clover | ChanLoader: com.a.a.n: java.net.ConnectException: Connection refused
I/Clover | ChanLoader: 	at com.a.a.b.a.a(BasicNetwork.java:148)
I/Clover | ChanLoader: 	at com.a.a.k.run(NetworkDispatcher.java:110)
I/Clover | ChanLoader: Caused by: java.net.ConnectException: Connection refused
I/Clover | ChanLoader: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
I/Clover | ChanLoader: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
I/Clover | ChanLoader: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
I/Clover | ChanLoader: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
I/Clover | ChanLoader: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
I/Clover | ChanLoader: 	at java.net.Socket.connect(Socket.java:605)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
I/Clover | ChanLoader: 	at com.android.okhttp.Connection.connectSocket(Connection.java:196)
I/Clover | ChanLoader: 	at com.android.okhttp.Connection.connect(Connection.java:172)
I/Clover | ChanLoader: 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
I/Clover | ChanLoader: 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
I/Clover | ChanLoader: 	at com.a.a.b.l.a(HurlStack.java:112)
I/Clover | ChanLoader: 	at com.a.a.b.a.a(BasicNetwork.java:96)
I/Clover | ChanLoader: 	... 1 more
I/Clover | ChanLoader: Loading error
I/Clover | ChanLoader: com.a.a.n: java.net.ConnectException: Connection refused
I/Clover | ChanLoader: 	at com.a.a.b.a.a(BasicNetwork.java:148)
I/Clover | ChanLoader: 	at com.a.a.k.run(NetworkDispatcher.java:110)
I/Clover | ChanLoader: Caused by: java.net.ConnectException: Connection refused
I/Clover | ChanLoader: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
I/Clover | ChanLoader: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
I/Clover | ChanLoader: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
I/Clover | ChanLoader: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
I/Clover | ChanLoader: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
I/Clover | ChanLoader: 	at java.net.Socket.connect(Socket.java:605)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
I/Clover | ChanLoader: 	at com.android.okhttp.Connection.connectSocket(Connection.java:196)
I/Clover | ChanLoader: 	at com.android.okhttp.Connection.connect(Connection.java:172)
I/Clover | ChanLoader: 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
I/Clover | ChanLoader: 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
I/Clover | ChanLoader: 	at com.a.a.b.l.a(HurlStack.java:112)
I/Clover | ChanLoader: 	at com.a.a.b.a.a(BasicNetwork.java:96)
I/Clover | ChanLoader: 	... 1 more
I/Clover | ChanLoader: Loading error
I/Clover | ChanLoader: com.a.a.n: java.net.ConnectException: Connection refused
I/Clover | ChanLoader: 	at com.a.a.b.a.a(BasicNetwork.java:148)
I/Clover | ChanLoader: 	at com.a.a.k.run(NetworkDispatcher.java:110)
I/Clover | ChanLoader: Caused by: java.net.ConnectException: Connection refused
I/Clover | ChanLoader: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
I/Clover | ChanLoader: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
I/Clover | ChanLoader: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
I/Clover | ChanLoader: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
I/Clover | ChanLoader: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
I/Clover | ChanLoader: 	at java.net.Socket.connect(Socket.java:605)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
I/Clover | ChanLoader: 	at com.android.okhttp.Connection.connectSocket(Connection.java:196)
I/Clover | ChanLoader: 	at com.android.okhttp.Connection.connect(Connection.java:172)
I/Clover | ChanLoader: 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
I/Clover | ChanLoader: 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
I/Clover | ChanLoader: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
I/Clover | ChanLoader: 	at com.a.a.b.l.a(HurlStack.java:112)
I/Clover | ChanLoader: 	at com.a.a.b.a.a(BasicNetwork.java:96)
I/Clover | ChanLoader: 	... 1 more
```

**Comment by Floens** [comment]
Clover doesn't do any special loading, just the normal http libraries are used.

The exception is ` Caused by: java.net.ConnectException: Connection refused`, what can indicate that something is blocking 4chan connections.
