### ISSUE TITLE
Clover-dev crashes when it's been left running in the background for too long

### ISSUE THREAD

**Issue by slyscorpion** [Floens/Clover#395]
I am running Clover-dev version 2.3.1-a6d58056. My OS is MIUI 9 version 8.1.18 (Android 7.1.1 with the January 1st security patch)

If you leave Clover-dev in the background for too long and then attempt to use it by going into your Recents menu and selecting it, the application crashes.

Steps to reproduce:

1. Open Clover-dev and a couple of other apps.
2. Leave Clover-dev and use some other app for a while (maybe an hour or so).
3. Open the Recents menu and select Clover-dev and at this point it should crash.

I also managed to get a log of sorts:

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.floens.chan.dev/org.floens.chan.ui.activity.BoardActivity}: java.lang.IllegalArgumentException: The view given to waitForMeasure is not attached to the window and does not have a ViewTreeObserver.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2740)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6372)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
Caused by: java.lang.IllegalArgumentException: The view given to waitForMeasure is not attached to the window and does not have a ViewTreeObserver.
	at org.floens.chan.a.a.a(AndroidUtils.java:322)
	at org.floens.chan.controller.a.d.a(PushControllerTransition.java:33)
	at org.floens.chan.controller.c.a(NavigationController.java:145)
	at org.floens.chan.ui.b.aw.a(ToolbarNavigationController.java:48)
	at org.floens.chan.ui.b.as.a(StyledToolbarNavigationController.java:62)
	at org.floens.chan.controller.c.a(NavigationController.java:54)
	at org.floens.chan.ui.b.as.a(StyledToolbarNavigationController.java:57)
	at org.floens.chan.controller.c.b(NavigationController.java:42)
	at org.floens.chan.ui.b.g.a(BrowseController.java:380)
	at org.floens.chan.ui.b.g.b(BrowseController.java:326)
	at org.floens.chan.ui.activity.a.b(StartActivity.java:215)
	at org.floens.chan.ui.activity.a.a(StartActivity.java:141)
	at org.floens.chan.ui.activity.a.onCreate(StartActivity.java:133)
	at android.app.Activity.performCreate(Activity.java:6861)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
	... 9 more

**Comment by Floens** [comment]
This was an issue with restoring the thread from the saved state. Fixed in https://github.com/Floens/Clover/commit/670d1ffdae264cb47e3963c7f3aada288c231db0

**Comment by slyscorpion** [comment]
Thanks for looking into this ;)
