### ISSUE TITLE
[BUG] App crashes on any android below Marshmallow because of a unicode symbol

### ISSUE THREAD

**Issue by K1rakishou** [Floens/Clover#677]
At least on the emulator. Here is the stacktrace:

```
04-14 16:05:13.229 4282-4282/? A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf0
04-14 16:05:13.229 4282-4282/? A/art: art/runtime/check_jni.cc:65]     string: '😴'
04-14 16:05:13.229 4282-4282/? A/art: art/runtime/check_jni.cc:65]     in call to NewStringUTF
04-14 16:05:13.229 4282-4282/? A/art: art/runtime/check_jni.cc:65]     from java.lang.String android.content.res.StringBlock.nativeGetString(long, int)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65] "main" prio=5 tid=1 Runnable
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x7492dfa8 self=0x7f5195197000
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   | sysTid=4282 nice=0 cgrp=apps sched=0/0 handle=0x7f519852c6a0
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=76 stm=7 core=0 HZ=100
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   | stack=0x7fff814c3000-0x7fff814c5000 stackSize=8MB
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   native: #00 pc 00006c19  /system/lib64/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned long, ucontext*)+57)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   native: #01 pc 0038aa50  /system/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+96)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   native: #02 pc 0035a617  /system/lib64/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+215)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   native: #03 pc 0010e1c3  /system/lib64/libart.so (art::JniAbort(char const*, char const*)+947)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   native: #04 pc 0010f13c  /system/lib64/libart.so (art::JniAbortF(char const*, char const*, ...)+220)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   native: #05 pc 00113706  /system/lib64/libart.so (art::ScopedCheck::Check(bool, char const*, ...) (.constprop.132)+1686)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   native: #06 pc 001196c0  /system/lib64/libart.so (art::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+64)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   native: #07 pc 000fdfdf  /system/lib64/libandroid_runtime.so (???)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   native: #08 pc 0033a1b3  /data/dalvik-cache/x86_64/system@framework@boot.oat (Java_android_content_res_StringBlock_nativeGetString__JI+187)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.content.res.StringBlock.nativeGetString(Native method)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.content.res.StringBlock.get(StringBlock.java:82)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   - locked <0x3c2b95f5> (a android.content.res.StringBlock)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.content.res.AssetManager.getPooledStringForCookie(AssetManager.java:272)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:972)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.content.res.TypedArray.getText(TypedArray.java:144)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.widget.TextView.<init>(TextView.java:917)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.widget.TextView.<init>(TextView.java:629)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:76)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:176)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:101)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1035)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1092)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   - locked <0x16bdaf8a> (a java.lang.Object[])
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at org.floens.chan.ui.layout.ThreadLayout.inflateEmptyView(ThreadLayout.java:585)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at org.floens.chan.ui.layout.ThreadLayout.switchVisible(ThreadLayout.java:560)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at org.floens.chan.ui.layout.ThreadLayout.showEmpty(ThreadLayout.java:261)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at org.floens.chan.core.presenter.ThreadPresenter.showNoContent(ThreadPresenter.java:106)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at org.floens.chan.ui.controller.ThreadController.showSitesNotSetup(ThreadController.java:107)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at org.floens.chan.ui.controller.BrowseController.showSitesNotSetup(BrowseController.java:98)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at org.floens.chan.ui.activity.StartActivity.restoreFresh(StartActivity.java:164)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at org.floens.chan.ui.activity.StartActivity.setupFromStateOrFreshLaunch(StartActivity.java:158)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at org.floens.chan.ui.activity.StartActivity.onCreate(StartActivity.java:142)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.app.Activity.performCreate(Activity.java:5937)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.app.ActivityThread.access$800(ActivityThread.java:144)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.os.Handler.dispatchMessage(Handler.java:102)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.os.Looper.loop(Looper.java:135)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at android.app.ActivityThread.main(ActivityThread.java:5221)
04-14 16:05:13.230 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke!(Native method)
04-14 16:05:13.231 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke(Method.java:372)
04-14 16:05:13.231 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
04-14 16:05:13.231 4282-4282/? A/art: art/runtime/check_jni.cc:65]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by K1rakishou** [comment]
I will fix it myself as a part of another task.
