### ISSUE TITLE
API parse error on 8ch /v/

### ISSUE THREAD

**Issue by u3shit** [Floens/Clover#685]
API parse error on 8ch /v/

Can't list threads on 8ch /v/ due to a json parse error. Other boards seem to work fine, only /v/ is affected.

Steps to reproduce the issue:
Open clover, select 8ch /v/ from the board list, API parse error appears. Relevant portion from logcat:
```04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader: Loading error
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader: com.android.a.s: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY                                                                                       
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader:     at org.floens.chan.core.f.c.a(JsonReaderRequest.java:69)                                                                                                                      
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader:     at com.android.a.g.run(NetworkDispatcher.java:121)
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY                                                                                             
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader:     at android.util.JsonReader.expect(JsonReader.java:310)
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader:     at android.util.JsonReader.beginObject(JsonReader.java:293)                                                                                                                   
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader:     at org.floens.chan.core.l.a.a.c.a(VichanApi.java:262)
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader:     at org.floens.chan.core.l.a.a.c.c(VichanApi.java:187)
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader:     at org.floens.chan.core.l.a.a.c.b(VichanApi.java:60)
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader:     at org.floens.chan.core.l.d.c.b(ChanReaderRequest.java:147)                                                                                                                   
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader:     at org.floens.chan.core.l.d.c.a(ChanReaderRequest.java:57)                                                                                                                    
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader:     at org.floens.chan.core.f.c.a(JsonReaderRequest.java:60)                                                                                                                      
04-18 08:58:09.243 11255 11255 I Clover | ChanThreadLoader:     ... 1 more
```

Android version: 8.1.0
Phone model: ONEPLUS A3003
Clover version: 3.0.2 F-Droid

**Comment by Adamantcheese** [comment]
[There appears to be a problem with this specific thread.](https://8ch.net/v/res/16365546.html) Notice how one of the files is fucked? This causes the json to spit out "extra_files":[[],{<image shit>}]. See how that first thing is an array instead of an object? Completely fucks the parsing. Literally the only instance in the entire board that has that. Why? Who the fuck knows. I blame Hotwheels.
